package com.burpmax.active;

import burp.IBurpExtenderCallbacks;
import burp.IExtensionHelpers;
import burp.IHttpRequestResponse;
import burp.IHttpService;
import burp.IRequestInfo;
import burp.IResponseInfo;
import burp.IParameter;

import com.burpmax.model.Finding;
import com.burpmax.store.FindingStore;

import java.net.URL;
import java.net.URLDecoder;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import java.util.function.*;
import java.util.stream.Collectors;
/**
 * Orchestrates all active probes against all in-scope endpoints.
 *
 * Run sequentially on a background thread.
 * Progress is reported via callbacks to the UI.
 */
public class ActiveScanner {

    private final IBurpExtenderCallbacks callbacks;
    private final IExtensionHelpers      helpers;
    private final FindingStore           store;

    // Progress tracking
    private final AtomicInteger  probesCompleted = new AtomicInteger(0);
    private final AtomicBoolean  cancelled       = new AtomicBoolean(false);
    private final AtomicBoolean  running         = new AtomicBoolean(false);
    private volatile boolean     isResuming      = false;  // set true only via startAsyncResume()

    // URLs generated by active probes — passive scanner must ignore these to
    // prevent probe payloads (traversal paths, SSRF URLs, canary strings) from
    // triggering passive findings on probe-generated traffic.
    // Bounded at 10,000 entries to prevent unbounded memory growth across long scans.
    private static final int MAX_PROBE_URLS = 10_000;
    private static final Set<String> PROBE_URLS =
            java.util.Collections.synchronizedSet(
                java.util.Collections.newSetFromMap(
                    new java.util.concurrent.ConcurrentHashMap<>()));

    /** Register a URL as probe-generated. Called by RequestBuilder on every probe request. */
    public static void registerProbeUrl(String url) {
        if (url != null && PROBE_URLS.size() < MAX_PROBE_URLS)
            PROBE_URLS.add(normaliseUrl(url));
    }

    /** Returns true if this URL was generated by an active probe. */
    public static boolean isProbeUrl(String url) {
        return url != null && PROBE_URLS.contains(normaliseUrl(url));
    }

    /** Clear probe URL registry when a scan completes or is cancelled. */
    public static void clearProbeUrls() {
        PROBE_URLS.clear();
        // The sensitive-file sweep is host-scoped and run-once; clearing it here
        // (called at every scan start and in run()'s finally) ensures a new scan
        // re-sweeps hosts instead of skipping them due to a previous scan's state.
        SensitiveFileProbe.resetSweptHosts();
        // Same per-host one-shot semantics for the smart-crawler sweep.
        SmartCrawlerProbe.resetSweptHosts();
    }

    private static String normaliseUrl(String url) {
        // Strip fragment and trailing slash for consistent matching
        int hash = url.indexOf('#');
        if (hash >= 0) url = url.substring(0, hash);
        return url.endsWith("/") && url.length() > 1 ? url.substring(0, url.length() - 1) : url;
    }

    // Configurable inter-request delay (ms). Default 150ms — safe for most targets.
    // 0 = no delay (fast, may trigger WAF/rate-limiting).
    private volatile int requestDelayMs = 150;

    // Hard cap on number of targets to prevent indefinitely long scans
    private static final int MAX_TARGETS = 500;

    // OOB client -- null means OOB probes are skipped (no false positives)
    private volatile OobClient oobClient = null;

    // How long to wait after all probes finish before polling for OOB interactions (ms).
    // DNS TTL propagation + server processing typically takes 10-60s.
    private volatile int oobPollDelayMs = 30_000;

    // Optional authenticated scan support.
    // When set, every probe request has auth headers injected automatically.
    private volatile AuthManager           authManager    = null;
    private volatile SessionHealthMonitor  healthMonitor  = null;

    // User-configured probe skip set (from scan policy UI).
    // Merged with automatic probeFilter() per-endpoint exclusions at dispatch time.
    private volatile Set<String> userSkipProbes = Set.of();

    // Callbacks wired from UI
    private Consumer<String>            onStatus;
    private BiConsumer<Integer,Integer> onProgress;
    private Runnable                    onComplete;
    private Consumer<String>            onLog;
    // Called with the probe name immediately before each probe executes
    private Consumer<String>            onProbeStart;

    public ActiveScanner(IBurpExtenderCallbacks callbacks,
                         IExtensionHelpers helpers,
                         FindingStore store) {
        this.callbacks = callbacks;
        this.helpers   = helpers;
        this.store     = store;
    }

    public void setOnStatus(Consumer<String> cb)             { this.onStatus     = cb; }
    public void setOnProgress(BiConsumer<Integer,Integer> cb){ this.onProgress   = cb; }
    public void setOnComplete(Runnable cb)                   { this.onComplete   = cb; }
    public void setOnLog(Consumer<String> cb)                { this.onLog        = cb; }
    public void setOnProbeStart(Consumer<String> cb)         { this.onProbeStart = cb; }
    public void setOobClient(OobClient client)               { this.oobClient    = client; }
    public void setOobPollDelayMs(int ms)                    { this.oobPollDelayMs = Math.max(0, ms); }
    public OobClient getOobClient()                          { return oobClient; }
    public void setRequestDelayMs(int ms)                    { this.requestDelayMs = Math.max(0, ms); }
    public int  getRequestDelayMs()                          { return requestDelayMs; }
    public boolean isRunning()                               { return running.get(); }
    public void    cancel()                                  { cancelled.set(true); }

    /**
     * Probe names that can be passed in a skipProbes set.
     * Any name listed here that also appears in runProbes() dispatch is skipped.
     */
    public static final Set<String> ALL_PROBE_NAMES = Set.of(
        "CSRF", "IDOR", "Open Redirect", "Auth Bypass", "GraphQL", "Rate Limit",
        "XSS", "SSTI", "Path Traversal", "XXE", "NoSQLi", "Prototype Pollution",
        "JWT", "SQLi", "LDAP", "CmdI", "SSRF", "Log4Shell", "File Upload",
        "Sensitive Files", "Smart Crawler", "Smuggling", "Mass Assignment",
        "Race Condition", "OAuth/OIDC",
        "Java Deserialization", "Hidden Params", "ViewState"
    );

    /**
     * Set probes to skip during the next scan. Merges with the automatic
     * probeFilter() exclusions (e.g. GraphQL skipped on non-GraphQL endpoints).
     * Persisted for the lifetime of this scanner instance.
     */
    public void setSkipProbes(Set<String> skip) {
        this.userSkipProbes = skip != null ? Set.copyOf(skip) : Set.of();
    }

    public Set<String> getSkipProbes() { return userSkipProbes; }

    /**
     * Scan a single pre-built request (from right-click context menu).
     * Runs on a daemon thread; does not reset PROBE_URLS or checkpoints.
     * Reports findings to the shared FindingStore.
     */
    public void scanSingleAsync(burp.IHttpRequestResponse item) {
        if (running.getAndSet(true)) {
            log("Scan already running - cannot start single-target scan. Cancel the active scan first.");
            return;
        }
        cancelled.set(false);
        Thread t = new Thread(() -> {
            try {
                ProbeContext ctx = buildProbeContext(item);
                if (ctx == null) {
                    status("Single scan: could not parse request (out of scope or static resource).");
                    return;
                }
                status("Single scan: " + ctx.url);
                RequestBuilder rb = new RequestBuilder(helpers);
                Set<String> skip = new HashSet<>(probeFilter(ctx));
                skip.addAll(userSkipProbes);
                List<ActiveScanResult> results = runProbes(ctx, rb, skip);
                for (ActiveScanResult r : results) {
                    Finding f = toFinding(r, ctx);
                    boolean isNew = store.add(f);
                    if (isNew) log("FOUND [single]: " + r.name + " | " + ctx.url);
                }

                // OOB poll phase - wait for DNS/HTTP callbacks from OOB probes.
                // Without this, findings from Log4Shell, Blind SQLi, XXE OOB, and
                // Blind CmdI are never reported because their fire-and-forget requests
                // need time for the server to make the outbound call.
                if (oobClient != null && oobClient.isAvailable() && !cancelled.get()) {
                    status("Single scan: waiting for OOB callbacks (" + (oobPollDelayMs / 1000) + "s)...");
                    long pollRemaining = oobPollDelayMs;
                    while (pollRemaining > 0 && !cancelled.get()) {
                        long sleep = Math.min(pollRemaining, 5_000);
                        try { Thread.sleep(sleep); } catch (InterruptedException e) { Thread.currentThread().interrupt(); break; }
                        pollRemaining -= sleep;
                    }
                    if (!cancelled.get()) {
                        List<OobClient.OobHit> oobHits = oobClient.pollAndMatch();
                        log("OOB poll [single]: " + oobHits.size() + " interaction(s) matched");
                        for (OobClient.OobHit hit : oobHits) {
                            ActiveScanResult r = buildOobFinding(hit);
                            if (r == null) continue;
                            // OOB hits carry their own endpoint; build a minimal Finding directly
                            com.burpmax.model.Finding f = new com.burpmax.model.Finding(
                                r.name, r.severity, r.description,
                                r.evidence, r.remediation, r.cwe,
                                ctx.host, hit.endpoint(), 0,
                                hit.probeRequestBytes(), null, ctx.service);
                            boolean isNew = store.add(f);
                            if (isNew) log("OOB FOUND [single]: " + r.name + " | " + hit.endpoint() + " | " + hit.parameter());
                        }
                    }
                }

                status("Single scan complete: " + results.size() + " finding(s) on " + ctx.url);
            } catch (Exception e) {
                log("Single scan error: " + e.getMessage());
                status("Single scan error: " + e.getMessage());
            } finally {
                running.set(false);
            }
        }, "burpmax-single-scan");
        t.setDaemon(true);
        t.start();
    }

    /**
     * Configure an authenticated scan session. When an AuthConfig is supplied,
     * all probe requests have auth headers injected automatically and the
     * session is refreshed on 401 (LOGIN mode) or warned on expiry (STATIC mode).
     * Pass null to run unauthenticated (default).
     *
     * Must be called before startAsync() / startAsyncResume().
     */
    public void setAuthConfig(AuthConfig config) {
        if (config == null) {
            this.authManager   = null;
            this.healthMonitor = null;
            return;
        }
        this.authManager = new AuthManager(config, callbacks, helpers, this::log);
        if (config.healthUrl != null) {
            this.healthMonitor = new SessionHealthMonitor(config, authManager,
                    callbacks, helpers, this::log);
        } else {
            this.healthMonitor = null;
        }
    }

    // ── Main entry point ──────────────────────────────────────────────────────

    public void startAsync() {
        if (running.getAndSet(true)) return;
        isResuming = false;
        cancelled.set(false);
        probesCompleted.set(0);
        ActiveScanner.clearProbeUrls();  // clear any stale probe URLs from previous scan
        Thread t = new Thread(this::run, "burpmax-active-scanner");
        t.setDaemon(true);
        t.start();
    }

    /**
     * Resume a previously interrupted scan from its checkpoint.
     * Called from UIBuilder when the user clicks "Active Scan" and
     * a valid checkpoint exists and they confirm the resume prompt.
     */
    public void startAsyncResume() {
        if (running.getAndSet(true)) return;
        isResuming = true;
        cancelled.set(false);
        probesCompleted.set(0);
        ActiveScanner.clearProbeUrls();  // clear any stale probe URLs from previous scan
        Thread t = new Thread(this::run, "burpmax-active-scanner");
        t.setDaemon(true);
        t.start();
    }

    private void run() {
        try {
            // ── Auth initialisation ────────────────────────────────────────────
            // Must happen before any probes fire so every HttpSender has a valid token.
            AuthManager   am = this.authManager;
            SessionHealthMonitor hm = this.healthMonitor;
            if (am != null) {
                status("Initialising authenticated session...");
                if (!am.initialise()) {
                    status("Auth initialisation failed - check auth config. Aborting scan.");
                    log("Auth initialisation failed. Scan aborted.");
                    return;
                }
                if (hm != null) hm.start();
                log("Authenticated scan ready (mode: " + am.getClass().getSimpleName() + ").");
            }

            status("Collecting in-scope endpoints from Burp site map...");

            List<ProbeContext> targets = collectTargets();
            if (targets.isEmpty()) {
                status("No in-scope endpoints found. Browse some pages first.");
                return;
            }

            // ── Link extraction pass ───────────────────────────────────────────
            status("Running link extraction to discover additional endpoints...");
            try {
                Set<String> inScopeHosts = new HashSet<>();
                for (ProbeContext ctx : targets) inScopeHosts.add(ctx.host);

                List<IHttpRequestResponse> newItems = LinkExtractor.extract(
                        callbacks, helpers, inScopeHosts, seenUrlsForExtraction(), onStatus);

                int before = targets.size();
                for (IHttpRequestResponse item : newItems) {
                    ProbeContext pctx = buildProbeContext(item);
                    if (pctx != null) targets.add(pctx);
                }
                int added = targets.size() - before;
                if (added > 0) log("Link extraction added " + added + " new endpoints.");
            } catch (Exception e) {
                log("Link extraction error (non-fatal): " + e.getMessage());
            }

            // Cap targets
            if (targets.size() > MAX_TARGETS) {
                log("Warning: " + targets.size() + " endpoints found. Capping at " + MAX_TARGETS + ".");
                targets = targets.subList(0, MAX_TARGETS);
            }

            // ── Checkpoint: fresh scan always starts clean ─────────────────────
            // A fresh "Active Scan" click always starts a new scan from scratch.
            // Resume path (isResuming=true) loads the saved checkpoint and skips
            // already-completed targets.
            // alreadyDone: used to seed progress bar on resume so it reflects true % done
            int alreadyDone = 0;
            // grandTotal: checkpoint totalTargets on resume, targets.size() on fresh scan
            int grandTotal  = 0;

            if (!isResuming) {
                ScanCheckpoint.clear(callbacks);
                grandTotal = targets.size();
            } else {
                // Resume: filter out already-completed targets from checkpoint
                ScanCheckpoint checkpoint = ScanCheckpoint.load(callbacks);
                if (checkpoint != null && checkpoint.hasPending()) {
                    final Set<String> done = checkpoint.completedUrls;
                    List<ProbeContext> remaining = targets.stream()
                            .filter(ctx -> !done.contains(ctx.url))
                            .collect(java.util.stream.Collectors.toList());
                    if (!remaining.isEmpty()) {
                        alreadyDone = done.size();
                        grandTotal  = checkpoint.totalTargets;
                        targets = remaining;
                        status(String.format("Resuming scan: %d/%d endpoints remaining (%d%% done)",
                                targets.size(), grandTotal, checkpoint.percentComplete()));
                        log(String.format("Scan resumed: skipping %d completed, %d remaining",
                                done.size(), targets.size()));
                    } else {
                        // All done — nothing to resume
                        status("Scan already complete - no remaining endpoints to scan.");
                        ScanCheckpoint.clear(callbacks);
                        return;
                    }
                } else {
                    // No valid checkpoint — fall back to full scan
                    isResuming = false;
                    grandTotal = targets.size();
                    ScanCheckpoint.clear(callbacks);
                }
            }

            // Create checkpoint for this scan run
            final List<String> allUrls = new ArrayList<>();
            for (ProbeContext ctx : targets) allUrls.add(ctx.url);
            ScanCheckpoint cp = ScanCheckpoint.start(allUrls);
            cp.save(callbacks);

            probesCompleted.set(alreadyDone);
            final int totalTargets = grandTotal > 0 ? grandTotal : targets.size();
            status("Found " + targets.size() + " endpoints. Starting active scan"
                    + (isResuming ? " (resumed)" : "") + "...");
            log("Active scan started: " + targets.size() + " targets" +
                    (alreadyDone > 0 ? " (" + alreadyDone + " already done)" : ""));

            // Show progress bar immediately so the UI never appears frozen during probes.
            // On resume this pre-fills the bar to the already-completed percentage.
            progress(probesCompleted.get(), totalTargets);

            RequestBuilder rb = new RequestBuilder(helpers);

            // Shuffle for stealth
            List<ProbeContext> shuffled = new ArrayList<>(targets);
            Collections.shuffle(shuffled, new java.util.Random());

            Set<String> seenFindings = Collections.synchronizedSet(new HashSet<>());
            java.util.concurrent.ConcurrentMap<String, java.util.concurrent.Semaphore> hostSems
                    = new java.util.concurrent.ConcurrentHashMap<>();

            // Thread-safe checkpoint reference for lambda capture
            final java.util.concurrent.atomic.AtomicReference<ScanCheckpoint> cpRef =
                    new java.util.concurrent.atomic.AtomicReference<>(cp);

            // ── Target-level parallelism ───────────────────────────────────────
            // Scan up to TARGET_THREADS endpoints concurrently.
            // Each endpoint runs its probes sequentially (one at a time) with a
            // 30s per-probe timeout. Net concurrency = TARGET_THREADS active
            // makeHttpRequest() calls, capped per-host by HOST_CONCURRENCY.
            final int TARGET_THREADS   = 2;   // endpoints scanned in parallel
            final int HOST_CONCURRENCY = 4;   // max concurrent requests to one host

            ExecutorService targetPool = Executors.newFixedThreadPool(TARGET_THREADS,
                    r -> { Thread t = new Thread(r, "burpmax-target"); t.setDaemon(true); return t; });

            List<java.util.concurrent.Future<?>> targetFutures = new ArrayList<>();
            final int remaining  = shuffled.size();    // targets to scan in this session
            final int total      = totalTargets;        // grand total (for progress bar denominator)
            final int doneOffset = alreadyDone;         // already-completed count (0 on fresh scan)

            for (int i = 0; i < remaining; i++) {
                if (cancelled.get()) break;
                final ProbeContext ctx = shuffled.get(i);
                // Display position accounts for already-completed targets on resume
                final int displayIdx = doneOffset + i;

                targetFutures.add(targetPool.submit(() -> {
                    if (cancelled.get()) return;

                    java.util.concurrent.Semaphore hostSem = hostSems.computeIfAbsent(
                            ctx.host, h -> new java.util.concurrent.Semaphore(HOST_CONCURRENCY));
                    // Acquire OUTSIDE the try/finally so a failed acquire never reaches
                    // hostSem.release() — releasing a permit we never took would corrupt
                    // the semaphore's permit count and allow >HOST_CONCURRENCY requests
                    // through to that host until it self-corrects.
                    try {
                        hostSem.acquire();
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt(); return;
                    }

                    try {
                        status(String.format("[%d/%d] Scanning: %s", displayIdx + 1, total, ctx.url));

                        List<ActiveScanResult> results = runProbes(ctx, rb, mergeSkip(probeFilter(ctx)));

                        for (ActiveScanResult r : results) {
                            String dedupKey = r.name + "|" + ctx.url + "|" + ctx.method + "|" + r.parameter;
                            if (seenFindings.add(dedupKey)) {
                                Finding f = toFinding(r, ctx);
                                boolean isNew = store.add(f);
                                if (isNew) log("FOUND: " + r.name + " | " + ctx.url + " | param: " + r.parameter);
                            }
                        }

                        // ── Save checkpoint after each completed target ────────
                        // Atomically update the checkpoint reference and persist to
                        // Burp settings. If Burp crashes after this point, resume
                        // will skip this target. Save is ~5ms on SSD; acceptable.
                        ScanCheckpoint updated = cpRef.updateAndGet(c -> c.markCompleted(ctx.url));
                        updated.save(callbacks);
                    } finally {
                        hostSem.release();
                        probesCompleted.incrementAndGet();
                        progress(probesCompleted.get(), total);
                    }
                }));
            }

            targetPool.shutdown();
            // Poll awaitTermination in 30s chunks instead of a single 3600s block.
            // This gives the user a heartbeat log entry every 30s if a probe hangs
            // despite the per-probe 30s timeout (e.g. interrupted flag not respected
            // by a native I/O call inside makeHttpRequest).
            try {
                int waitedSecs = 0;
                final int MAX_WAIT_SECS = 3600;
                while (!targetPool.awaitTermination(30, TimeUnit.SECONDS)) {
                    waitedSecs += 30;
                    if (cancelled.get()) {
                        log("Scan cancelled - waiting for active probes to stop...");
                    } else {
                        log("Waiting for probe threads to complete (" + waitedSecs + "s elapsed)...");
                    }
                    if (waitedSecs >= MAX_WAIT_SECS) {
                        log("Warning: probe threads did not finish within " + MAX_WAIT_SECS + "s - forcing shutdown.");
                        targetPool.shutdownNow();
                        break;
                    }
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                targetPool.shutdownNow();
            }

            // ---- OOB poll phase -------------------------------------------------
            if (oobClient != null && oobClient.isAvailable()) {
                status("Waiting for OOB callbacks (" + (oobPollDelayMs / 1000) + "s)...");
                log("OOB poll: waiting " + oobPollDelayMs + "ms for DNS/HTTP callbacks");

                // Wait in 500ms chunks — exit immediately if scan cancelled
                long pollRemaining = oobPollDelayMs;
                while (pollRemaining > 0 && !cancelled.get()) {
                    long chunk = Math.min(pollRemaining, 500);
                    try { Thread.sleep(chunk); }
                    catch (InterruptedException e) { Thread.currentThread().interrupt(); break; }
                    pollRemaining -= chunk;
                }

                if (!cancelled.get()) {
                    List<OobClient.OobHit> oobHits = oobClient.pollAndMatch();
                    log("OOB poll complete: " + oobHits.size() + " interaction(s) matched");
                    for (OobClient.OobHit hit : oobHits) {
                        ActiveScanResult r = buildOobFinding(hit);
                        if (r == null) continue;
                        String dedupKey = r.name + "|" + hit.endpoint() + "|" + hit.parameter();
                        if (seenFindings.add(dedupKey)) {
                            ProbeContext ctx = targets.stream()
                                    .filter(t -> t.url.equals(hit.endpoint())).findFirst().orElse(null);
                            if (ctx == null) ctx = targets.isEmpty() ? null : targets.get(0);
                            if (ctx != null) {
                                Finding f = toFinding(r, ctx);
                                boolean isNew = store.add(f);
                                if (isNew) log("OOB FOUND: " + r.name + " | " + hit.endpoint() + " | " + hit.parameter());
                            }
                        }
                    }
                } else {
                    log("OOB poll skipped - scan cancelled.");
                }
            }
            // ---------------------------------------------------------------------

            int found = (int) store.getAll().stream()
                    .filter(f -> f.name.startsWith("[ACTIVE]")).count();
            status("Active scan complete. " + found + " active findings.");
            log("Active scan complete: " + targets.size() + " endpoints scanned, " + found + " findings.");

        } catch (Exception e) {
            status("Active scan error: " + e.getMessage());
            log("Active scan error: " + e);
        } finally {
            running.set(false);
            ActiveScanner.clearProbeUrls();
            // Stop health monitor before closing OOB client
            try { if (healthMonitor != null) healthMonitor.stop(); } catch (Exception ignored) {}
            // Always close OobClient -- whether scan completes, is cancelled, or errors.
            // Previously only closed in the OOB poll block, leaking the HTTP polling
            // connection on cancel or scan error.
            try { if (oobClient != null) oobClient.close(); } catch (Exception ignored) {}
            // Clear checkpoint only on clean completion -- on cancel or error,
            // preserve it so the scan can be resumed from where it left off.
            if (!cancelled.get()) {
                ScanCheckpoint.clear(callbacks);
            }
            // Only fire onComplete for natural completion, not user-initiated cancel.
            if (!cancelled.get() && onComplete != null) onComplete.run();
        }
    }

    // ── Probe orchestration ───────────────────────────────────────────────────

    // Probes run sequentially per endpoint on the target thread, one at a time.
    // Endpoint-level parallelism is controlled by TARGET_THREADS in run().

    // ── Probe filtering ───────────────────────────────────────────────────────

    /**
     * Returns a set of probe names to SKIP for this endpoint based on context.
     * Skipping irrelevant probes is the single biggest speed improvement:
     *   - A logout/unsubscribe endpoint with no params needs no SQLi/SSTI/XSS
     *   - A non-JSON endpoint doesn't need NoSQLi or Prototype Pollution
     *   - An endpoint with no auth headers doesn't need JWT or Auth Bypass
     *   - A non-HTML response doesn't need XSS
     */
    private static Set<String> probeFilter(ProbeContext ctx) {
        Set<String> skip = new HashSet<>();
        String urlLower   = ctx.url.toLowerCase();
        String ctLower    = ctx.contentType != null ? ctx.contentType.toLowerCase() : "";
        boolean hasParams = !ctx.allParamNames().isEmpty();
        boolean hasBody   = ctx.bodyRaw != null && !ctx.bodyRaw.isBlank();
        boolean hasJson   = !ctx.jsonParams.isEmpty();
        boolean hasAuth   = ctx.reqHeaders.containsKey("authorization")
                         || ctx.reqHeaders.containsKey("cookie");
        boolean isGet     = "GET".equalsIgnoreCase(ctx.method);

        // No parameters at all — skip injection-based probes entirely.
        // Header-based probes (Log4Shell, CORS, HostHeader, SSRF) still run.
        // Rate limit check also skipped — it only makes sense on login/API endpoints.
        if (!hasParams) {
            skip.add("SQLi");
            skip.add("SSTI");
            skip.add("XSS");
            skip.add("CmdI");
            skip.add("XXE");
            skip.add("NoSQLi");
            skip.add("Path Traversal");
            skip.add("Open Redirect");
            skip.add("IDOR");
            skip.add("Prototype Pollution");
            skip.add("LDAP");
            skip.add("Rate Limit");
        }

        // Non-JSON body — skip JSON-specific probes
        if (!hasJson && !ctLower.contains("json")) {
            skip.add("NoSQLi");
            skip.add("Prototype Pollution");
        }

        // Non-XML body — skip XXE
        if (!ctLower.contains("xml") && (ctx.bodyRaw == null || !ctx.bodyRaw.trim().startsWith("<"))) {
            skip.add("XXE");
        }

        // No auth — skip auth-dependent probes
        if (!hasAuth) {
            skip.add("JWT");
            skip.add("Auth Bypass");
            skip.add("IDOR");
        }

        // GET requests — skip state-changing-specific probes (CSRF only matters on POST/PUT/DELETE)
        if (isGet) {
            skip.add("CSRF");
        }

        // Logout / unsubscribe / signout — low value, high noise
        if (urlLower.contains("/logout") || urlLower.contains("/signout")
                || urlLower.contains("/unsubscribe") || urlLower.contains("/revoke")) {
            skip.add("SQLi");
            skip.add("SSTI");
            skip.add("XSS");
            skip.add("CmdI");
            skip.add("NoSQLi");
            skip.add("LDAP");
        }

        // Static-like paths — skip injection probes
        if (urlLower.contains("/static/") || urlLower.contains("/assets/")
                || urlLower.contains("/public/") || urlLower.contains("/vendor/")) {
            skip.add("SQLi"); skip.add("SSTI"); skip.add("XSS");
            skip.add("CmdI"); skip.add("XXE"); skip.add("LDAP");
        }

        // GraphQL only on likely GraphQL endpoints
        if (!urlLower.contains("graphql") && !urlLower.contains("/gql")
                && !urlLower.contains("/query") && !hasJson) {
            skip.add("GraphQL");
        }

        // OAuth/OIDC only on OAuth-like endpoints (probe self-gates, but skip early for speed)
        if (!urlLower.contains("/oauth") && !urlLower.contains("/authorize")
                && !urlLower.contains("/token") && !urlLower.contains("/oidc")
                && !urlLower.contains("/openid") && !urlLower.contains("/connect")
                && !urlLower.contains("/sso") && !urlLower.contains("/auth/")) {
            skip.add("OAuth/OIDC");
        }

        // Race condition only on POST/PUT (probe self-gates to coupon/payment/resource families)
        if (isGet || ctx.method.equalsIgnoreCase("DELETE")) {
            skip.add("Race Condition");
        }

        // ViewState only on WebForms endpoints (probe self-gates, but skip early for speed)
        boolean hasViewstateField = ctx.allParamNames().stream()
                .anyMatch(p -> p.toLowerCase().startsWith("__viewstate")
                            || p.toLowerCase().equals("__eventtarget")
                            || p.toLowerCase().equals("__eventvalidation"));
        if (!hasViewstateField) {
            skip.add("ViewState");
        }

        // Java deserialization only on POST/PUT with binary/base64 body
        if (isGet) {
            skip.add("Java Deserialization");
        }

        // Smuggling already has reverse-proxy guard, skip on non-HTTP/1.1 hints
        // (already handled inside the probe — no additional filter needed)

        return skip;
    }

    /** Merges automatic per-endpoint filters with user-configured skip set. */
    private Set<String> mergeSkip(Set<String> autoSkip) {
        if (userSkipProbes.isEmpty()) return autoSkip;
        Set<String> merged = new HashSet<>(autoSkip);
        merged.addAll(userSkipProbes);
        return merged;
    }

    private List<ActiveScanResult> runProbes(ProbeContext ctx, RequestBuilder rb) {
        return runProbes(ctx, rb, Collections.emptySet());
    }

    private List<ActiveScanResult> runProbes(ProbeContext ctx, RequestBuilder rb,
                                              Set<String> skipProbes) {
        if (cancelled.get()) return List.of();

        // Register this target's base URL so the passive scanner can identify
        // probe-generated traffic from path traversal, SSRF, and other probes.
        ActiveScanner.registerProbeUrl(ctx.url);

        // ── Probe ordering: fast-first, slow-last, shuffle within each tier ─────
        //
        // Probes are divided into 4 tiers by expected execution time:
        //
        //   Tier 1 — Instant  (~1 request, no confirmation)
        //            CORS, Host Header, CSRF, IDOR, Open Redirect, Auth Bypass,
        //            GraphQL introspection
        //
        //   Tier 2 — Fast     (2–4 requests with confirmation, <3s per param)
        //            XSS, SSTI, Path Traversal, XXE in-band, NoSQLi, LDAP error,
        //            Prototype Pollution, JWT, HTTP Smuggling
        //
        //   Tier 3 — Medium   (OOB probes + multi-request confirmation, 3–15s)
        //            SQLi error-based, SSRF in-band, Log4Shell OOB,
        //            OOB SQLi/CmdI/SSTI/PP, XXE OOB, LDAP OOB
        //
        //   Tier 4 — Slow     (time-based sleep per param, 3s–60s+)
        //            SQLi time-based, CmdI time-based
        //
        // Within each tier, probes are shuffled for stealth (prevents fixed
        // fingerprint in access logs). Across tiers, ordering is strict —
        // Tier 1 always completes before Tier 4 starts.

        List<Map.Entry<String, Callable<List<ActiveScanResult>>>> tier1 = new ArrayList<>();
        List<Map.Entry<String, Callable<List<ActiveScanResult>>>> tier2 = new ArrayList<>();
        List<Map.Entry<String, Callable<List<ActiveScanResult>>>> tier3 = new ArrayList<>();
        List<Map.Entry<String, Callable<List<ActiveScanResult>>>> tier4 = new ArrayList<>();

        java.util.Random rng = new java.util.Random();

        // ── Tier 1: Instant — 1 request, no per-param loops ──────────────────
        tier1.add(Map.entry("CORS",         () -> CorsMisconfigProbe.probe(ctx, rb, newSender())));
        tier1.add(Map.entry("Host Header",  () -> HostHeaderProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("CSRF"))
            tier1.add(Map.entry("CSRF",     () -> CsrfProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("IDOR"))
            tier1.add(Map.entry("IDOR",     () -> IdorProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("Open Redirect"))
            tier1.add(Map.entry("Open Redirect", () -> OpenRedirectProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("Auth Bypass"))
            tier1.add(Map.entry("Auth Bypass", () -> AuthBypassProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("GraphQL"))
            tier1.add(Map.entry("GraphQL",  () -> GraphQlProbe.probe(ctx, rb, newSender())));
        // OAuth/OIDC misconfiguration probe — mostly passive checks + 2 short active checks.
        // Runs in Tier 1 because it self-gates to OAuth endpoints and most sub-checks
        // do not send additional requests.
        if (!skipProbes.contains("OAuth/OIDC"))
            tier1.add(Map.entry("OAuth/OIDC", () -> OAuthOidcProbe.probe(ctx, rb, newSender())));

        // Rate limit active probe: sends 6 identical requests and checks for throttling.
        // Runs in Tier 1 (fast, 6 identical requests) so the result is available early.
        // Only meaningful on endpoints with params (login, search, OTP, reset, API).
        if (!skipProbes.contains("Rate Limit"))
            tier1.add(Map.entry("Rate Limit", () -> {
                com.burpmax.scanner.CheckResult cr =
                        com.burpmax.scanner.RateLimitChecker.checkActive(
                                newSender(), ctx.service, ctx.originalRequest, ctx.url);
                if (cr == null) return List.of();
                // Convert CheckResult into an ActiveScanResult for consistent handling
                return List.of(new ActiveScanResult(
                        cr.name, cr.severity, cr.description,
                        cr.evidence, cr.remediation, cr.cwe,
                        ctx.url, "(active probe)",
                        "6x identical requests sent",
                        null, null));
            }));

        // ── Tier 2: Fast — 2–4 requests with confirmation, no sleep ──────────
        if (!skipProbes.contains("XSS"))
            tier2.add(Map.entry("XSS",         () -> XssProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("XSS"))
            tier2.add(Map.entry("Stored XSS",  () -> StoredXssProbe.probe(ctx, rb, newSender(),
                    siteMapSinkProvider())));
        // DOM XSS analyses the response JavaScript, not request parameters, so it
        // is NOT gated by the params-based "XSS" skip — it runs on every endpoint
        // that returns HTML/JS, including parameterless pages (a SPA shell is the
        // single most common DOM XSS surface).
        tier2.add(Map.entry("DOM XSS",         () -> XssProbe.probeDomOnly(ctx, newSender())));
        tier2.add(Map.entry("Sensitive Files", () -> SensitiveFileProbe.probe(ctx, rb, newSender())));
        // Smart crawler: tech-aware sensitive endpoint discovery with generic
        // wordlist fallback. Self-gates to one sweep per host per scan.
        tier2.add(Map.entry("Smart Crawler",   () -> SmartCrawlerProbe.probe(ctx, rb, newSender())));
        // File upload probe self-gates: it returns immediately unless the request
        // is multipart/form-data with a file part, so it is safe to always register.
        tier2.add(Map.entry("File Upload",     () -> FileUploadProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("SSTI"))
            tier2.add(Map.entry("SSTI",         () -> SstiProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("Path Traversal"))
            tier2.add(Map.entry("Path Traversal", () -> PathTraversalProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("XXE"))
            tier2.add(Map.entry("XXE",          () -> XxeProbe.probe(ctx, rb, newSender(), oobClient)));
        if (!skipProbes.contains("NoSQLi"))
            tier2.add(Map.entry("NoSQLi",       () -> NoSqlInjectionProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("Prototype Pollution"))
            tier2.add(Map.entry("Prototype Pollution", () -> PrototypePollutionProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("JWT"))
            tier2.add(Map.entry("JWT",          () -> JwtProbe.probe(ctx, rb, newSender(), oobClient)));
        tier2.add(Map.entry("Smuggling",        () -> HttpRequestSmugglingProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("Mass Assignment"))
            tier2.add(Map.entry("Mass Assignment", () -> MassAssignmentProbe.probe(ctx, rb, newSender())));
        // Race condition probe: 20 parallel requests to detect TOCTOU vulnerabilities.
        // Self-gates tightly to coupon/payment/limited-resource endpoints only.
        // Requires callbacks reference for direct makeHttpRequest (bypasses per-request delay).
        if (!skipProbes.contains("Race Condition"))
            tier2.add(Map.entry("Race Condition", () -> RaceConditionProbe.probe(ctx, rb, newSender(), callbacks)));

        // ── Tier 3: Medium — OOB probes, SQLi error-based, multi-request ──────
        // Error-based SQLi (no sleep) runs in tier 3 because it loops over all
        // params × error payloads — medium total request count but fast per-request.
        // OOB probes fire-and-forget; the wait happens in the OOB poll phase.
        if (!skipProbes.contains("SQLi"))
            tier3.add(Map.entry("SQLi-error",   () -> SqliProbe.probeErrorBased(ctx, rb, newSender())));
        if (!skipProbes.contains("SQLi"))
            tier3.add(Map.entry("SQLi-OOB",     () -> OobSqliProbe.probe(ctx, rb, newSender(), oobClient)));
        if (!skipProbes.contains("LDAP"))
            tier3.add(Map.entry("LDAP",         () -> LdapInjectionProbe.probe(ctx, rb, newSender(), oobClient)));
        if (!skipProbes.contains("CmdI"))
            tier3.add(Map.entry("CmdI-output",  () -> CommandInjectionProbe.probeOutputBased(ctx, rb, newSender())));
        if (!skipProbes.contains("CmdI"))
            tier3.add(Map.entry("CmdI-OOB",     () -> BlindCmdiProbe.probe(ctx, rb, newSender(), oobClient)));
        if (!skipProbes.contains("SSTI"))
            tier3.add(Map.entry("SSTI-OOB",     () -> BlindSstiProbe.probe(ctx, rb, newSender(), oobClient)));
        if (!skipProbes.contains("Prototype Pollution"))
            tier3.add(Map.entry("PP-OOB",       () -> BlindPrototypePollutionProbe.probe(ctx, rb, newSender(), oobClient)));
        tier3.add(Map.entry("SSRF",             () -> SsrfProbe.probe(ctx, rb, newSender(), oobClient)));
        tier3.add(Map.entry("Log4Shell",        () -> Log4ShellProbe.probe(ctx, rb, newSender(), oobClient)));
        if (!skipProbes.contains("Java Deserialization"))
            tier3.add(Map.entry("Java Deserialization", () -> JavaDeserializationProbe.probe(ctx, rb, newSender(), oobClient)));
        if (!skipProbes.contains("Hidden Params"))
            tier3.add(Map.entry("Hidden Params", () -> HiddenParamProbe.probe(ctx, rb, newSender())));
        if (!skipProbes.contains("ViewState"))
            tier3.add(Map.entry("ViewState",    () -> ViewStateProbe.probe(ctx, rb, newSender(), oobClient)));

        // ── Tier 4: Slow — time-based sleep per param, always last ───────────
        // These block the probe thread for SLEEP_SECS * 2 per confirmed param.
        // Putting them last means all fast findings are already reported to the
        // UI before we start waiting on sleep payloads.
        if (!skipProbes.contains("SQLi"))
            tier4.add(Map.entry("SQLi-time",    () -> SqliProbe.probeTimeBased(ctx, rb, newSender())));
        if (!skipProbes.contains("CmdI"))
            tier4.add(Map.entry("CmdI-time",    () -> CommandInjectionProbe.probeTimeBased(ctx, rb, newSender())));

        // Shuffle within each tier for stealth — prevents fixed probe fingerprint
        Collections.shuffle(tier1, rng);
        Collections.shuffle(tier2, rng);
        Collections.shuffle(tier3, rng);
        Collections.shuffle(tier4, rng);

        // Assemble final ordered task list: T1 → T2 → T3 → T4
        List<Map.Entry<String, Callable<List<ActiveScanResult>>>> tasks = new ArrayList<>();
        tasks.addAll(tier1);
        tasks.addAll(tier2);
        tasks.addAll(tier3);
        tasks.addAll(tier4);

        // ── Sequential execution with per-probe timeout ───────────────────────
        // Probes run ONE AT A TIME on the calling target thread in tier order.
        // This ensures:
        //   1. Tier ordering is strictly respected (Tier 1 finishes before Tier 4 starts)
        //   2. No thread explosion (was 2 × 8 = 16 concurrent makeHttpRequest() calls)
        //   3. Each probe has a 30s wall-clock timeout via a daemon Future so a
        //      single hung makeHttpRequest() never freezes the entire scan
        //
        // Endpoint-level parallelism (TARGET_THREADS=2) provides the concurrency.
        ExecutorService timeoutPool = Executors.newCachedThreadPool(
                r -> { Thread t = new Thread(r, "burpmax-probe-to"); t.setDaemon(true); return t; });

        List<ActiveScanResult> all = new ArrayList<>();

        try {
            for (Map.Entry<String, Callable<List<ActiveScanResult>>> task : tasks) {
                if (cancelled.get()) break;
                final String probeName = task.getKey();
                // Notify UI of which probe is starting so progress bar can show probe name
                if (onProbeStart != null) onProbeStart.accept(probeName);
                Future<List<ActiveScanResult>> f = timeoutPool.submit(() -> {
                    if (cancelled.get()) return List.of();
                    try { return task.getValue().call(); }
                    catch (Exception e) { log("Probe error [" + probeName + "]: " + e.getMessage()); return List.of(); }
                });
                try {
                    List<ActiveScanResult> results = f.get(30, TimeUnit.SECONDS);
                    if (results != null) all.addAll(results);
                    // Run passive scanner on probe responses to catch secrets, version
                    // disclosures, and header misconfigs in error responses triggered by probes.
                    // This mirrors what Burp Pro does: passive checks run on ALL traffic.
                    runPassiveOnProbeResults(results);
                } catch (TimeoutException e) {
                    f.cancel(true);
                    log("Probe timeout [" + probeName + "] on " + ctx.url + " - skipping");
                } catch (InterruptedException e) {
                    f.cancel(true);
                    Thread.currentThread().interrupt();
                    break;
                } catch (Exception e) {
                    log("Probe failed [" + probeName + "]: " + e.getMessage());
                }
            }
        } finally {
            // shutdownNow() in finally ensures the pool is always reclaimed even
            // if an Error (OOM, StackOverflow) propagates out of the probe loop.
            // Under normal conditions the outer run() catch(Exception) already
            // protects against RuntimeException — this is defensive hygiene only.
            timeoutPool.shutdownNow();
        }
        return all;
    }

    /** Creates a fresh HttpSender with the current delay setting and shared cancel flag. */
    private HttpSender newSender() {
        HttpSender s = new HttpSender(callbacks, helpers, requestDelayMs, cancelled);
        if (authManager != null) s.setAuthManager(authManager);
        return s;
    }

    /**
     * Supplies same-host GET requests harvested from the Burp site map so the
     * Stored XSS probe can check whether a submitted canary surfaces on a
     * DIFFERENT page (comments, profile, dashboard, admin view).
     *
     * Only GET requests to the same host are returned; static resources are
     * excluded (they cannot render a stored payload). The result is capped to
     * keep the per-injection cost bounded — StoredXssProbe further caps how
     * many it actually sends (MAX_SINKS).
     */
    private StoredXssProbe.SinkProvider siteMapSinkProvider() {
        return (String host) -> {
            List<byte[]> out = new ArrayList<>();
            try {
                IHttpRequestResponse[] items = callbacks.getSiteMap(null);
                if (items == null) return out;
                Set<String> seen = new HashSet<>();
                for (IHttpRequestResponse item : items) {
                    if (out.size() >= 40) break;          // hard cap on harvest size
                    byte[] req = item.getRequest();
                    if (req == null) continue;
                    try {
                        IRequestInfo ri = helpers.analyzeRequest(item);
                        if (!"GET".equalsIgnoreCase(ri.getMethod())) continue;
                        java.net.URL u = ri.getUrl();
                        if (u == null || !u.getHost().equalsIgnoreCase(host)) continue;
                        if (!callbacks.isInScope(u)) continue;
                        String path = u.getPath() == null ? "" : u.getPath().toLowerCase();
                        if (isStaticResource(path)) continue;
                        if (isSkippableUrl(u.toString())) continue;
                        // Dedup by URL so we don't re-check the same page repeatedly.
                        if (!seen.add(u.toString())) continue;
                        out.add(req);
                    } catch (Exception ignored) {}
                }
            } catch (Exception ignored) {}
            return out;
        };
    }

    // ── Link extraction helpers ───────────────────────────────────────────────

    /**
     * Build the set of URL+method keys already collected from the site map.
     * Passed to LinkExtractor so it doesn't re-fetch already-known URLs.
     */
    private Set<String> seenUrlsForExtraction() {
        Set<String> seen = new HashSet<>();
        try {
            IHttpRequestResponse[] items = callbacks.getSiteMap(null);
            if (items == null) return seen;
            for (IHttpRequestResponse item : items) {
                if (item.getRequest() == null) continue;
                try {
                    IRequestInfo ri = helpers.analyzeRequest(item);
                    seen.add(ri.getMethod() + ":" + ri.getUrl().toString());
                    seen.add(ri.getUrl().toString()); // also plain URL for LinkExtractor dedup
                } catch (Exception ignored) {}
            }
        } catch (Exception ignored) {}
        return seen;
    }

    /**
     * Convert a freshly fetched IHttpRequestResponse into a ProbeContext.
     * Mirrors the parsing logic in collectTargets — kept in sync manually.
     * Returns null if the item is out of scope, static, or unparseable.
     */
    private ProbeContext buildProbeContext(IHttpRequestResponse item) {
        try {
            byte[] req  = item.getRequest();
            byte[] resp = item.getResponse();
            if (req == null) return null;

            IRequestInfo reqInfo = helpers.analyzeRequest(item);
            URL url = reqInfo.getUrl();
            if (!callbacks.isInScope(url)) return null;

            String path = url.getPath() != null ? url.getPath().toLowerCase() : "";
            if (isStaticResource(path)) return null;
            if (isSkippableUrl(url.toString())) return null;

            IHttpService svc = item.getHttpService();
            if (svc == null) {
                final String _host  = url.getHost();
                final int    _port  = url.getPort() > 0 ? url.getPort()
                                    : "https".equalsIgnoreCase(url.getProtocol()) ? 443 : 80;
                final String _proto = url.getProtocol();
                svc = new IHttpService() {
                    public String getHost()     { return _host; }
                    public int    getPort()     { return _port; }
                    public String getProtocol() { return _proto; }
                };
            }

            boolean isHttps = "https".equalsIgnoreCase(svc.getProtocol());

            Map<String, String> queryParams = parseQueryParams(url.getQuery());
            Map<String, String> bodyParams  = new LinkedHashMap<>();
            Map<String, String> jsonParams  = new LinkedHashMap<>();
            Map<String, String> xmlParams   = new LinkedHashMap<>();
            String bodyRaw = "";
            String reqCT   = "";

            Map<String, String> reqHeaders = new LinkedHashMap<>();
            List<String> headers = reqInfo.getHeaders();
            for (int i = 1; i < headers.size(); i++) {
                String h = headers.get(i);
                int colon = h.indexOf(':');
                if (colon > 0) {
                    String k = h.substring(0, colon).trim().toLowerCase();
                    String v = h.substring(colon + 1).trim();
                    reqHeaders.put(k, v);
                    if ("content-type".equals(k)) reqCT = v;
                }
            }

            int bodyOffset = reqInfo.getBodyOffset();
            if (req.length > bodyOffset) {
                bodyRaw = helpers.bytesToString(Arrays.copyOfRange(req, bodyOffset, req.length));
                String ctLower = reqCT.toLowerCase();
                if (ctLower.contains("application/x-www-form-urlencoded")) {
                    bodyParams = parseQueryParams(bodyRaw);
                } else if (ctLower.contains("application/json")) {
                    flattenJson(bodyRaw, "", jsonParams);
                } else if (ctLower.contains("xml")) {
                    com.burpmax.active.XmlBodyParser.flatten(bodyRaw, xmlParams);
                }
            }

            for (IParameter p : reqInfo.getParameters()) {
                if (p.getType() == IParameter.PARAM_URL)
                    queryParams.putIfAbsent(p.getName(), p.getValue());
                else if (p.getType() == IParameter.PARAM_BODY)
                    bodyParams.putIfAbsent(p.getName(), p.getValue());
            }

            return new ProbeContext(svc, req, resp,
                    url.toString(), reqInfo.getMethod(),
                    url.getHost(), isHttps,
                    queryParams, bodyParams, jsonParams, xmlParams,
                    bodyRaw, reqCT, reqHeaders);
        } catch (Exception e) { return null; }
    }

    // ── Target collection ─────────────────────────────────────────────────────

    private List<ProbeContext> collectTargets() {
        List<ProbeContext> targets = new ArrayList<>();
        Set<String> seen = new HashSet<>();

        try {
            IHttpRequestResponse[] items = callbacks.getSiteMap(null);
            if (items == null) return targets;

            for (IHttpRequestResponse item : items) {
                try {
                    byte[] req  = item.getRequest();
                    byte[] resp = item.getResponse();
                    if (req == null) continue;

                    IRequestInfo reqInfo = helpers.analyzeRequest(item);
                    URL url = reqInfo.getUrl();

                    // Only in-scope
                    if (!callbacks.isInScope(url)) continue;

                    // Dedup by URL + method
                    String key = reqInfo.getMethod() + ":" + url.toString();
                    if (!seen.add(key)) continue;

                    // Skip static resources
                    String path = url.getPath() != null ? url.getPath().toLowerCase() : "";
                    if (isStaticResource(path)) continue;

                    // Skip Socket.IO / WebSocket / long-poll URLs — these are
                    // persistent connections that will hang the scanner thread.
                    if (isSkippableUrl(url.toString())) continue;

                    IHttpService svc = item.getHttpService();
                    boolean isHttps  = "https".equalsIgnoreCase(svc.getProtocol());

                    // Parse parameters
                    Map<String, String> queryParams = parseQueryParams(url.getQuery());
                    Map<String, String> bodyParams  = new LinkedHashMap<>();
                    Map<String, String> jsonParams  = new LinkedHashMap<>();
                    Map<String, String> xmlParams   = new LinkedHashMap<>();
                    String bodyRaw  = "";
                    String reqCT    = "";

                    // Parse headers
                    Map<String, String> reqHeaders = new LinkedHashMap<>();
                    List<String> headers = reqInfo.getHeaders();
                    for (int i = 1; i < headers.size(); i++) {
                        String h = headers.get(i);
                        int colon = h.indexOf(':');
                        if (colon > 0) {
                            String k = h.substring(0, colon).trim().toLowerCase();
                            String v = h.substring(colon + 1).trim();
                            reqHeaders.put(k, v);
                            if ("content-type".equals(k)) reqCT = v;
                        }
                    }

                    // Parse body parameters
                    int bodyOffset = reqInfo.getBodyOffset();
                    if (req.length > bodyOffset) {
                        bodyRaw = helpers.bytesToString(
                                Arrays.copyOfRange(req, bodyOffset, req.length));
                        String ctLower = reqCT.toLowerCase();
                        if (ctLower.contains("application/x-www-form-urlencoded")) {
                            bodyParams = parseQueryParams(bodyRaw);
                        } else if (ctLower.contains("application/json")) {
                            // Flatten JSON body into dot-notation paths so every
                            // leaf value becomes an independently injectable parameter.
                            flattenJson(bodyRaw, "", jsonParams);
                        } else if (ctLower.contains("xml")) {
                            // Flatten XML body leaf nodes into dot-notation paths.
                            // e.g. <user><name>alice</name></user>
                            //   → {"user.name": "alice"}
                            com.burpmax.active.XmlBodyParser.flatten(bodyRaw, xmlParams);
                        }
                    }

                    // Parse Burp parameter objects (query + form-encoded only;
                    // JSON params come from our own flattener above)
                    for (IParameter p : reqInfo.getParameters()) {
                        String pname = p.getName();
                        String pval  = p.getValue();
                        if (p.getType() == IParameter.PARAM_URL) {
                            queryParams.putIfAbsent(pname, pval);
                        } else if (p.getType() == IParameter.PARAM_BODY) {
                            bodyParams.putIfAbsent(pname, pval);
                        }
                    }

                    ProbeContext pctx = new ProbeContext(
                            svc, req, resp,
                            url.toString(), reqInfo.getMethod(),
                            url.getHost(), isHttps,
                            queryParams, bodyParams, jsonParams, xmlParams,
                            bodyRaw, reqCT, reqHeaders);
                    // Always add endpoints: even parameterless ones are tested
                    // by header-injection probes (Log4Shell, SSRF, HostHeader, CORS).
                    // Only skip truly parameterless GET endpoints where no
                    // header probes fire either — i.e. never skip entirely.
                    targets.add(pctx);

                } catch (Exception ignored) {}
            }
        } catch (Exception e) {
            log("Error collecting targets: " + e.getMessage());
        }
        return targets;
    }

    private static boolean isStaticResource(String path) {
        // Skip static file extensions
        if (path.matches(".*\\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|" +
                         "mp4|mp3|pdf|zip|tar|gz|map)$")) return true;
        // Skip Socket.IO / Engine.IO polling and WebSocket upgrade endpoints —
        // these are long-lived connections that will hang the scanner indefinitely.
        // Patterns: /socket.io/, EIO=, transport=polling, transport=websocket
        String lower = path.toLowerCase();
        if (lower.contains("/socket.io") || lower.contains("/engine.io")) return true;
        return false;
    }

    private static boolean isSkippableUrl(String fullUrl) {
        if (fullUrl == null) return false;
        String lower = fullUrl.toLowerCase();
        // Skip WebSocket upgrade URLs
        if (lower.startsWith("ws://") || lower.startsWith("wss://")) return true;
        // Skip long-poll / SSE / Socket.IO query params regardless of path
        if (lower.contains("transport=polling") || lower.contains("transport=websocket")) return true;
        if (lower.contains("eio=") && lower.contains("socket.io")) return true;
        // Skip Server-Sent Events endpoints
        if (lower.contains("/events") && lower.contains("text/event-stream")) return true;
        return false;
    }

    private static Map<String, String> parseQueryParams(String query) {
        Map<String, String> map = new LinkedHashMap<>();
        if (query == null || query.isEmpty()) return map;
        for (String pair : query.split("&")) {
            int eq = pair.indexOf('=');
            if (eq < 0) continue;
            try {
                String k = URLDecoder.decode(pair.substring(0, eq), "UTF-8");
                String v = URLDecoder.decode(pair.substring(eq + 1), "UTF-8");
                map.put(k, v);
            } catch (Exception ignored) {}
        }
        return map;
    }

    /**
     * Recursively flatten a JSON object/array body into a map of dot-notation
     * paths → string-serialised leaf values, using the same lightweight string
     * scanner as RequestBuilder (no JSONObject API — avoids stub limitations).
     *
     * Examples:
     *   {"username":"alice","pass":"s3cr3t"}
     *     → {"username":"alice", "pass":"s3cr3t"}
     *
     *   {"user":{"name":"alice","age":30},"active":true}
     *     → {"user.name":"alice", "user.age":"30", "active":"true"}
     *
     *   {"ids":[1,2],"tags":["a","b"]}
     *     → {"ids.0":"1", "ids.1":"2", "tags.0":"a", "tags.1":"b"}
     *
     * @param json   raw JSON body string
     * @param prefix current dot-path prefix ("" for root call)
     * @param out    map to populate with path → value entries
     */
    private static void flattenJson(String json, String prefix, Map<String, String> out) {
        if (json == null) return;
        json = json.trim();
        if (json.isEmpty()) return;
        if (json.length() > 65_536) return;   // guard against huge payloads

        try {
            JsonWalker.flattenAt(json, 0, prefix, out, 0);
        } catch (Exception ignored) {
            // Malformed JSON — silently skip
        }
    }

    // ── Conversion ────────────────────────────────────────────────────────────

    /** Route an OOB hit to the correct probe's finding builder. */
    private static ActiveScanResult buildOobFinding(OobClient.OobHit hit) {
        String name = hit.probeName();
        if (name.equals("Log4Shell / Log4j RCE"))           return Log4ShellProbe.buildFinding(hit);
        if (name.equals("Blind XXE (OOB)"))                  return XxeProbe.buildOobFinding(hit);
        if (name.equals("SSRF (OOB)"))                       return buildGenericOobFinding(hit);
        if (name.equals("LDAP Injection (Blind OOB)"))       return LdapInjectionProbe.buildFinding(hit);
        if (name.equals("OS Command Injection (Blind OOB)")) return BlindCmdiProbe.buildFinding(hit);
        if (name.startsWith("SSTI → RCE (Blind OOB)"))      return BlindSstiProbe.buildFinding(hit);
        if (name.startsWith("SQL Injection (OOB DNS)"))      return OobSqliProbe.buildFinding(hit);
        if (name.startsWith("Prototype Pollution → RCE"))   return BlindPrototypePollutionProbe.buildFinding(hit);
        if (name.equals("JWT x5u SSRF"))                      return buildGenericOobFinding(hit);
        return buildGenericOobFinding(hit);
    }

    private static ActiveScanResult buildGenericOobFinding(OobClient.OobHit hit) {
        return new ActiveScanResult(
            hit.probeName(), com.burpmax.model.Finding.SEV_HIGH,
            "An out-of-band " + hit.interactionType() + " interaction was received from " +
            hit.endpoint() + " after injecting payload into '" + hit.parameter() + "'. " +
            "This confirms that the server initiated an outbound connection to the OOB host, " +
            "which is a strong indicator of a server-side request forgery or injection vulnerability.",
            "OOB: " + hit.interactionDetail() + " | Param: " + hit.parameter() +
            " | Payload: " + hit.payload(),
            "Investigate the injection point and determine the root cause. " +
            "Restrict outbound network access from the app tier.",
            "CWE-918",
            hit.endpoint(), hit.parameter(), hit.payload(), "", hit.interactionDetail(),
            hit.probeRequestBytes(), null, -1L);
    }

    /**
     * Runs the passive scanner over any response bytes carried by active probe results.
     * Catches version disclosures, secrets, security headers, and other passive findings
     * in error responses generated by active probes — the same behaviour as Burp Pro.
     *
     * Only processes results that carry non-null probeResponseBytes to avoid double-scanning
     * the same response (the original request/response is already handled by BurpExtender
     * via the IHttpListener path).
     */
    private void runPassiveOnProbeResults(List<ActiveScanResult> probeResults) {
        if (probeResults == null || probeResults.isEmpty()) return;
        for (ActiveScanResult r : probeResults) {
            if (r == null || r.probeResponseBytes == null) continue;
            if (r.probeRequestBytes == null) continue;
            try {
                // Parse probe request headers for context (method, URL, etc.)
                burp.IRequestInfo reqInfo  = helpers.analyzeRequest(r.probeRequestBytes);
                burp.IResponseInfo respInfo = helpers.analyzeResponse(r.probeResponseBytes);
                if (reqInfo == null || respInfo == null) continue;

                int statusCode = respInfo.getStatusCode();
                if (statusCode == 404) continue;  // same filter as BurpExtender.process()

                // Parse response headers
                java.util.Map<String, String> respHdrs  = new java.util.LinkedHashMap<>();
                java.util.List<String>        setCookies = new java.util.ArrayList<>();
                java.util.List<String>        hdrs = respInfo.getHeaders();
                int hdrStart = hdrs.size() > 1 ? 1 : 0;
                for (String h : hdrs.subList(hdrStart, hdrs.size())) {
                    int c = h.indexOf(':');
                    if (c < 0) continue;
                    String k = h.substring(0, c).trim().toLowerCase();
                    String v = h.substring(c + 1).trim();
                    respHdrs.put(k, v);
                    if ("set-cookie".equals(k)) setCookies.add(v);
                }

                // Response body (limit 256KB)
                int bodyOff = Math.min(respInfo.getBodyOffset(), r.probeResponseBytes.length);
                int bodyLen = Math.min(r.probeResponseBytes.length - bodyOff, 256_000);
                String body = helpers.bytesToString(
                        java.util.Arrays.copyOfRange(r.probeResponseBytes, bodyOff, bodyOff + bodyLen));

                // Request headers and body
                java.util.Map<String, String> reqHdrs = new java.util.LinkedHashMap<>();
                for (String h : reqInfo.getHeaders()) {
                    int c = h.indexOf(':');
                    if (c < 0) continue;
                    reqHdrs.put(h.substring(0, c).trim().toLowerCase(), h.substring(c + 1).trim());
                }
                int reqBodyOff = reqInfo.getBodyOffset();
                String reqBody = reqBodyOff < r.probeRequestBytes.length
                        ? helpers.bytesToString(java.util.Arrays.copyOfRange(
                              r.probeRequestBytes, reqBodyOff, r.probeRequestBytes.length))
                        : "";

                java.net.URL urlObj = reqInfo.getUrl();
                String url  = urlObj != null ? urlObj.toString() : r.endpoint;
                String host = urlObj != null ? urlObj.getHost()  : r.endpoint;
                String ct   = respHdrs.getOrDefault("content-type", "");

                // Dispatch through the passive scanner — reuses all 13 existing checkers
                java.util.List<com.burpmax.model.Finding> passiveFindings =
                    com.burpmax.scanner.Dispatcher.dispatch(
                        reqHdrs, respHdrs, setCookies,
                        body, ct,
                        reqInfo.getMethod(),
                        host, url, statusCode,
                        reqBody,
                        r.probeRequestBytes, r.probeResponseBytes,
                        null);  // null httpService is safe: UIBuilder.sendToRepeater() null-checks
                               // svcObj before casting, and FindingStore passes it through verbatim.
                               // These findings will show "cannot send to Repeater" but won't NPE.

                for (com.burpmax.model.Finding f : passiveFindings) {
                    // Tag the source so findings pane shows these came from active probe responses
                    f.analystNote = "Detected in active probe response (not original traffic)";
                    boolean isNew = store.add(f);
                    if (isNew) log("[PASSIVE-ON-PROBE] " + f.name + " | " + url);
                }
            } catch (Exception e) {
                // Non-fatal — passive scan on probe responses must never abort the active scan
                log("runPassiveOnProbeResults error (non-fatal): " + e.getMessage());
            }
        }
    }

    private Finding toFinding(ActiveScanResult r, ProbeContext ctx) {
        int sc = ctx.originalResponse != null ? extractStatusFromResponse(ctx.originalResponse) : 0;
        // Store the original traffic as the primary raw request/response
        // so passive checkers and the Repeater button work correctly.
        // The probe-specific data (mutated request, probe response, payload, timing)
        // is carried separately for PoC rendering.
        com.burpmax.model.Finding f = new com.burpmax.model.Finding(
                r.name, r.severity, r.description,
                r.evidence, r.remediation, r.cwe,
                ctx.host, ctx.url, sc,
                ctx.originalRequest, ctx.originalResponse, ctx.service);
        // Patch the primary EndpointEntry with probe-specific PoC data
        if (!f.affectedEndpoints.isEmpty()) {
            com.burpmax.model.Finding.EndpointEntry orig = f.affectedEndpoints.get(0);
            f.affectedEndpoints.set(0, new com.burpmax.model.Finding.EndpointEntry(
                    orig.endpoint, orig.statusCode,
                    orig.rawRequest, orig.rawResponse, orig.httpService,
                    r.probeRequestBytes, r.probeResponseBytes,
                    r.payload, r.parameter, r.timingMs));
        }
        return f;
    }

    private static int extractStatusFromResponse(byte[] resp) {
        if (resp == null || resp.length < 12) return 0;
        try {
            String start = new String(resp, 0, Math.min(20, resp.length));
            String[] parts = start.split(" ", 3);
            return parts.length > 1 ? Integer.parseInt(parts[1].trim()) : 0;
        } catch (Exception e) { return 0; }
    }

    // ── UI callbacks ──────────────────────────────────────────────────────────

    private void status(String msg) {
        if (onStatus != null) onStatus.accept(msg);
    }
    private void progress(int done, int total) {
        if (onProgress != null) onProgress.accept(done, total);
    }
    private void log(String msg) {
        if (onLog != null) onLog.accept(msg);
    }
}
